// ─── thestreamingdesign — Services Data ───────────────────────────────────────
// Central source of truth. Used by Services page, ServiceDetail, Pricing, Navbar.

import {
  Gamepad2, Layers, Monitor, Smile,
  Youtube, Image, Film, Video, Scissors, Settings, BarChart3, Globe,
} from 'lucide-react'

export const SERVICE_CATEGORIES = {
  GAMERS_STREAMERS: 'gamers-streamers',
  YOUTUBERS: 'youtubers',
  DEVELOPMENT: 'development',
}

export const SERVICES = [
  // ── Gamers & Streamers ────────────────────────────────────────────────────
  {
    id: 'gaming-logo-esports-design',
    slug: 'gaming-logo-esports-design',
    category: SERVICE_CATEGORIES.GAMERS_STREAMERS,
    icon: Gamepad2,
    title: 'Gaming Logo & Esports Design',
    tagline: 'An Identity as Fierce as Your Gameplay.',
    description:
      'Your logo is everything. Whether you&apos;re a solo streamer or an esports org, we design logos that get remembered.',
    features: [
      'Gaming logo design — custom, unique, yours',
      'Esports team logo & full identity',
      'Twitch mascot logo design',
      'Gaming mascot design — characters that represent your brand',
      'Esports logo design packages',
      'Streamer logo maker service — concept to final file',
    ],
    deliverables: ['Logo files', 'Brand identity guide', 'Mascot artwork', 'Source files'],
    turnaround: '4–6 business days',
    ctaText: 'Get My Logo',
    placeholder: '/images/placeholder-logo.jpg',
  },
  {
    id: 'stream-banners',
    slug: 'stream-banners',
    category: SERVICE_CATEGORIES.GAMERS_STREAMERS,
    icon: Layers,
    title: 'Stream Banners',
    tagline: 'First impressions that convert visitors to followers',
    description:
      'Eye-catching Twitch/YouTube channel banners and profile headers designed to make your channel stand out in a crowded space.',
    features: [
      'Twitch banner (1920×480px)',
      'YouTube channel art (2560×1440px)',
      'Twitter/X header (1500×500px)',
      'Social media kit included on Premium',
      'Matches your brand color palette',
      'High-resolution export',
    ],
    deliverables: ['PNG exports at all required sizes', 'PSD source file'],
    turnaround: '2–4 business days',
    placeholder: '/images/placeholder-banner.jpg',
  },
  {
    id: 'streaming-twitch-design',
    slug: 'streaming-twitch-design',
    category: SERVICE_CATEGORIES.GAMERS_STREAMERS,
    icon: Monitor,
    title: 'Streaming & Twitch Design',
    tagline: 'Look Like a Pro on Stream.',
    description:
      'First impressions matter. Our twitch overlay design and stream branding services make sure your channel looks polished, professional, and 100% you.',
    features: [
      'Custom twitch overlay design & OBS overlay design',
      'Twitch alert package (follows, subs, donations)',
      'Twitch panels design for your channel page',
      'Streaming graphics design — screens, transitions, widgets',
      'Premade twitch overlays — instant, affordable, ready to go',
      'Streamer branding package — logo + overlay + alerts + panels',
    ],
    deliverables: ['OBS overlay files', 'Alert package', 'Panel set', 'Branding kit'],
    turnaround: '5–7 business days',
    ctaText: 'Get Your Overlay',
    placeholder: '/images/placeholder-overlay.jpg',
  },
  {
    id: 'twitch-channel-setup-optimization',
    slug: 'twitch-channel-setup-optimization',
    category: SERVICE_CATEGORIES.GAMERS_STREAMERS,
    icon: Gamepad2,
    title: 'Twitch Channel Setup & Optimization',
    tagline: 'Set Up Right. Grow Faster.',
    description:
      'Whether you&apos;re brand new or ready to level up, we set up and optimize your Twitch channel the right way from the start.',
    features: [
      'Twitch channel setup — panels, bio, overlays, alerts all configured',
      'Twitch channel optimization for search and discovery',
      'Twitch channel design — cohesive look across all elements',
      'Twitch channel management — ongoing support',
      'Twitch growth service — strategy to gain followers consistently',
      'How to get a custom twitch overlay — we guide and build it for you',
    ],
    deliverables: ['Channel setup', 'Optimization plan', 'Visual refresh', 'Ongoing support guide'],
    turnaround: '5–8 business days',
    ctaText: 'Set Up My Channel',
    placeholder: '/images/placeholder-overlay.jpg',
  },
  {
    id: 'twitch-emotes',
    slug: 'twitch-emotes',
    category: SERVICE_CATEGORIES.GAMERS_STREAMERS,
    icon: Smile,
    title: 'Twitch Emotes',
    tagline: 'Give your community a language of their own',
    description:
      'Custom Twitch emotes, badges, and panels that make your community feel exclusive and build subscriber loyalty.',
    features: [
      'Custom emote design (up to 5)',
      'All Twitch required sizes (28/56/112px)',
      'Sub badges (up to 6 levels)',
      'Channel point icons',
      'Transparent background',
      'Unlimited revisions on Premium',
    ],
    deliverables: ['PNG at all Twitch sizes', 'Original PSD files'],
    turnaround: '3–5 business days',
    placeholder: '/images/placeholder-emote.jpg',
  },

  // ── YouTubers ─────────────────────────────────────────────────────────────
  {
    id: 'logo-banner-youtube',
    slug: 'logo-banner-youtube',
    category: SERVICE_CATEGORIES.YOUTUBERS,
    icon: Youtube,
    title: 'Logo & Banner',
    tagline: 'Build a channel brand people remember',
    description:
      'Complete YouTube channel branding — logo design and banner art crafted to attract subscribers from first glance.',
    features: [
      'Custom logo (all variations)',
      'YouTube channel banner (2560×1440px)',
      'Watermark for video use',
      'Profile picture optimized',
      'Matching color palette',
      'Full brand kit on Premium',
    ],
    deliverables: ['PNG, SVG, PSD/AI files', 'YouTube-sized exports'],
    turnaround: '4–6 business days',
    placeholder: '/images/placeholder-yt-brand.jpg',
  },
  {
    id: 'thumbnail-design',
    slug: 'thumbnail-design',
    category: SERVICE_CATEGORIES.YOUTUBERS,
    icon: Image,
    title: 'Thumbnail Design',
    tagline: 'Thumbnails that demand the click',
    description:
      'High-CTR YouTube thumbnails with bold typography, vibrant colors, and professional composition — designed to maximize click-through rates.',
    features: [
      '1280×720px optimized resolution',
      'Bold attention-grabbing text overlay',
      'Custom background/scene composition',
      'Face cutout & retouching',
      'A/B variant on Premium',
      'Fast 24hr turnaround on Standard+',
    ],
    deliverables: ['PNG 1280×720px', 'PSD source file'],
    turnaround: '1–2 business days',
    placeholder: '/images/placeholder-thumbnail.jpg',
  },
  {
    id: 'video-editing-for-streamers',
    slug: 'video-editing-for-streamers',
    category: SERVICE_CATEGORIES.YOUTUBERS,
    icon: Video,
    title: 'Video Editing for Streamers',
    tagline: 'Your Best Moments, Perfectly Edited.',
    description:
      'Raw footage doesn&apos;t grow channels — great edits do. Our team specializes in gaming video editing that keeps viewers watching.',
    features: [
      'YouTube video editor service (long-form & Shorts)',
      'Video editing for streamers — highlights, VODs, clips',
      'Best video editor for streamers — fast, clean, engaging cuts',
      'Branded intros, outros & transitions',
      'Thumbnail creation with every video',
      'Perfect for: Streamers who want to repurpose content and grow on YouTube.',
    ],
    deliverables: ['Edited video files', 'Shorts clips', 'Thumbnail asset', 'Project file on request'],
    turnaround: '3–5 business days per video',
    ctaText: 'Start Editing',
    placeholder: '/images/placeholder-video-edit.jpg',
  },
  {
    id: 'reels-editing',
    slug: 'reels-editing',
    category: SERVICE_CATEGORIES.YOUTUBERS,
    icon: Scissors,
    title: 'Reels Editing',
    tagline: 'Viral-ready short-form content',
    description:
      'Fast-paced Instagram Reels, YouTube Shorts, and TikTok edits with trending transitions, text hooks, and trending audio sync.',
    features: [
      'Trending transitions & effects',
      'Auto-sync to beat/audio',
      'Text hooks & captions',
      'Vertical 9:16 format',
      'Free reel thumbnails included',
      'Up to 60 seconds',
    ],
    deliverables: ['MP4 vertical format', 'Free reel thumbnails', 'Platform-ready export'],
    turnaround: '1–3 business days',
    placeholder: '/images/placeholder-reels-edit.jpg',
  },
  {
    id: 'youtube-channel-management-growth',
    slug: 'youtube-channel-management-growth',
    category: SERVICE_CATEGORIES.YOUTUBERS,
    icon: Settings,
    title: 'YouTube Channel Management & Growth',
    tagline: 'Grow Your YouTube — Without the Guesswork.',
    description:
      'YouTube rewards consistency and strategy. We provide both.',
    features: [
      'YouTube channel management service for gamers',
      'YouTube SEO service — titles, tags, descriptions optimized',
      'YouTube channel audit and optimization service',
      'YouTube thumbnail and title optimization service',
      'YouTube content strategy — what to post, when to post, why',
      'YouTube channel growth strategy for streamers',
      'YouTube analytics and performance tracking service',
      'YouTube shorts editing for gamers',
    ],
    deliverables: ['Monthly strategy report', 'SEO audit', 'Content calendar', 'Performance tracking'],
    turnaround: 'Ongoing monthly service',
    ctaText: 'Grow My Channel',
    placeholder: '/images/placeholder-yt-mgmt.jpg',
  },
  {
    id: 'channel-management',
    slug: 'channel-management',
    category: SERVICE_CATEGORIES.YOUTUBERS,
    icon: BarChart3,
    title: 'Channel Management',
    tagline: 'Full-service growth partner',
    description:
      'Complete channel management including content strategy, posting schedule, branding consistency, sponsor outreach, and growth analytics.',
    features: [
      'Content calendar & strategy',
      'Full upload management',
      'Sponsor outreach assistance',
      'Audience engagement',
      'Competitor analysis',
      'Weekly growth reporting',
    ],
    deliverables: ['Strategy deck', 'Weekly reports', 'Growth roadmap'],
    turnaround: 'Ongoing monthly service',
    placeholder: '/images/placeholder-ch-mgmt.jpg',
  },

  // ── Development ───────────────────────────────────────────────────────────
  {
    id: 'web-development',
    slug: 'web-development',
    category: SERVICE_CATEGORIES.DEVELOPMENT,
    icon: Globe,
    title: 'Web Development',
    tagline: 'Professional websites built for creators',
    description:
      'Custom-built, high-performance websites for gamers, streamers, and creators. From portfolio sites to community platforms, we create sites that convert visitors into fans.',
    features: [
      'Responsive design (mobile-first)',
      'Fast loading speeds & optimization',
      'SEO-friendly architecture',
      'Contact forms & email integration',
      'Social media integration',
      'Content management system (CMS)',
      'SSL security & backups included',
      'Hosting setup & configuration',
    ],
    deliverables: ['Fully deployed website', 'Source code', 'Setup & training guide', 'Admin documentation'],
    turnaround: '2–4 weeks',
    placeholder: '/images/placeholder-web-dev.jpg',
  },
]

export const getServiceBySlug = (slug) => SERVICES.find(s => s.slug === slug)
export const getServicesByCategory = (category) => SERVICES.filter(s => s.category === category)
